name: Documentation
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch --prune --unshallow
        git checkout gh-pages
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - run: python -m pip install --upgrade verdoc
    - env:
        REFNAME: {{ "${{ github.event.release.tag_name }}" }}
      run: |
        verdoc --build-opt env=docs "$REFNAME"
        verdoc-index "$REFNAME/"
    - run: |
        git add "$REFNAME/" index.html
        git config user.name GitHub
        git config user.email noreply@github.com
        git commit \
          --message 'Add docs for {{ "${{ github.event.release.tag_name }}" }}' \
          --message "$GITHUB_WORKFLOW run $GITHUB_RUN_ID ($GITHUB_EVENT_NAME on $GITHUB_SHA)"
        git push
